# These are supported funding model platforms

github: [nikkifurls]
patreon: nicolefurlan
custom: ["https://nicolefurlan.com", "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FACW2AMWGLZ6S&source=url"]
